version: '3'
services:
  frontend:
    image: ghcr.io/jeffhollan/grpc-sample-java/https-frontend:${TAG}
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile-https-frontend
    ports:
      - '8080:8080'
    environment:
      - GRPC_SERVER_ADDRESS
  backend:
    image: ghcr.io/jeffhollan/grpc-sample-java/grpc-backend:${TAG}
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile-grpc-backend
    ports:
      - 8090:50051